# statefulset
#---
#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: slow
#provisioner: kubernetes.io/gce-pd
#parameters:
#  type: pd-standard
#  fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi